
export const TRANSLATIONS = {
  en: {
    title: "Welcome Back",
    subtitle: "Sign in to continue",
    emailLabel: "Email Address",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    rememberMe: "Remember Me",
    forgotPassword: "Forgot Password?",
    loginButton: "Sign In",
    orSeparator: "OR",
    ssoSeparator: "Single Sign-On",
    loginWith: "Sign in with",
    magicLink: "Sign in with Magic Link",
    authenticator: "Use Authenticator App",
    biometrics: "Sign in with Biometrics",
    okta: "Sign in with Okta",
    azureAd: "Sign in with Azure AD",
    noOptions: "No login methods are enabled.",
    configurePrompt: "Please use the panel to enable at least one login method.",
    configPanelTitle: "Auth Module Configuration",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    language: "Language",
    english: "English",
    hindi: "Hindi",
    providers: "Providers",
    emailPassword: "Email / Password",
    socialLogins: "Social Logins",
    passwordless: "Passwordless",
    sso: "Enterprise SSO",
    features: "Features",
  },
  hi: {
    title: "वापसी पर स्वागत है",
    subtitle: "जारी रखने के लिए साइन इन करें",
    emailLabel: "ईमेल पता",
    emailPlaceholder: "आप@उदाहरण.कॉम",
    passwordLabel: "पासवर्ड",
    rememberMe: "मुझे याद रखना",
    forgotPassword: "पासवर्ड भूल गए?",
    loginButton: "साइन इन करें",
    orSeparator: "या",
    ssoSeparator: "एकल साइन-ऑन",
    loginWith: "इसके साथ साइन इन करें",
    magicLink: "मैजिक लिंक से साइन इन करें",
    authenticator: "प्रमाणक ऐप का उपयोग करें",
    biometrics: "बायोमेट्रिक्स से साइन इन करें",
    okta: "ओक्टा के साथ साइन इन करें",
    azureAd: "एज़्योर एडी के साथ साइन इन करें",
    noOptions: "कोई लॉगिन विधि सक्षम नहीं है।",
    configurePrompt: "कृपया कम से कम एक लॉगिन विधि सक्षम करने के लिए पैनल का उपयोग करें।",
    configPanelTitle: "प्रामाणिकता मॉड्यूल कॉन्फ़िगरेशन",
    theme: "थीम",
    light: "प्रकाश",
    dark: "अंधेरा",
    language: "भाषा",
    english: "अंग्रेजी",
    hindi: "हिन्दी",
    providers: "प्रदाता",
    emailPassword: "ईमेल / पासवर्ड",
    socialLogins: "सोशल लॉगिन",
    passwordless: "पासवर्ड रहित",
    sso: "एंटरप्राइज एसएसओ",
    features: "विशेषताएँ",
  },
};
